// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheatricalPlayersRefactoringKata.Infra.Context;

#nullable disable

namespace TheatricalPlayersRefactoringKata.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.33");

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Domain.Entity.Play", b =>
                {
                    b.Property<int>("Lines")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.ToTable("Play");

                    b.HasDiscriminator<string>("PlayType").HasValue("Play");
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Application.Genres.Comedy", b =>
                {
                    b.HasBaseType("TheatricalPlayersRefactoringKata.Domain.Entity.Play");

                    b.HasDiscriminator().HasValue("Comedy");
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Application.Genres.History", b =>
                {
                    b.HasBaseType("TheatricalPlayersRefactoringKata.Domain.Entity.Play");

                    b.HasDiscriminator().HasValue("History");
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Application.Genres.Tragedy", b =>
                {
                    b.HasBaseType("TheatricalPlayersRefactoringKata.Domain.Entity.Play");

                    b.HasDiscriminator().HasValue("Tragedy");
                });
#pragma warning restore 612, 618
        }
    }
}
