// <auto-generated />
using System;
using ApprovalTests.Approvers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TheatricalPlayersAPI.Migrations
{
    [DbContext(typeof(TheatricalDbContext))]
    partial class TheatricalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TheatricalPlayersAPI.Models.InvoiceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("TheatricalPlayersAPI.Models.PerformanceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Audience")
                        .HasColumnType("int");

                    b.Property<int?>("InvoiceModelId")
                        .HasColumnType("int");

                    b.Property<string>("PlayGenre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PlayId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceModelId");

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("TheatricalPlayersAPI.Models.PlayModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<int>("Lines")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Plays");
                });

            modelBuilder.Entity("TheatricalPlayersAPI.Models.PerformanceModel", b =>
                {
                    b.HasOne("TheatricalPlayersAPI.Models.InvoiceModel", null)
                        .WithMany("Performances")
                        .HasForeignKey("InvoiceModelId");
                });

            modelBuilder.Entity("TheatricalPlayersAPI.Models.InvoiceModel", b =>
                {
                    b.Navigation("Performances");
                });
#pragma warning restore 612, 618
        }
    }
}
