openapi: 3.0.3
info:
  title: Printer API
  description: API for printing statements
  version: 1.0.0

servers:
  - url: http://localhost:5000/api/

paths:
  /all:
    get:
      summary: Get all statements
      responses:
        200:
          description: List of statements
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Statement'
  /all/add:
    post:
      summary: Create a new statement
      requestBody:
        description: Statement to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Statement'
      responses:
        201:
          description: Statement created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Statement'
  /all/delete/{id}:
    delete:
      summary: Delete a statement by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Statement deleted successfully
        404:
          description: Statement not found
  /all/{id}:
    get:
      summary: Get a statement by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Statement found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Statement'
        404:
          description: Statement not found

components:
  schemas:
    Statement:
      type: object
      properties:
        id:
          type: integer
        details:
          type: string