// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheatricalPlayersRefactoringKata.API.Data;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(TheaterAppDbContext))]
    [Migration("20241219104250_NovaMigracao")]
    partial class NovaMigracao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.API.Data.InvoiceRecordEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatementXml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Performance", b =>
                {
                    b.Property<string>("PlayId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Audience")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InvoiceRecordEntityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayId");

                    b.HasIndex("InvoiceRecordEntityId");

                    b.ToTable("Performance");
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Performance", b =>
                {
                    b.HasOne("TheatricalPlayersRefactoringKata.API.Data.InvoiceRecordEntity", null)
                        .WithMany("Performances")
                        .HasForeignKey("InvoiceRecordEntityId");
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.API.Data.InvoiceRecordEntity", b =>
                {
                    b.Navigation("Performances");
                });
#pragma warning restore 612, 618
        }
    }
}
