// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheatricalPlayersRefactoringKata.Infrastructure.Data;

#nullable disable

namespace TheatricalPlayersRefactoringKata.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.33");

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Domain.Entities.InvoiceCalculeteSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumAudience")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PerAudience")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PerAudienceAdditional")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("InvoiceCalculeteSettings");
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Domain.Entities.InvoiceCreditSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BonusCreditPerAttendees")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumAudience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("InvoiceCreditSettings");
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Domain.Entities.PlayType", b =>
                {
                    b.Property<int>("PlayTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlayTypeId");

                    b.ToTable("PlayType");
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Domain.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InvoiceId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Domain.Performance", b =>
                {
                    b.Property<int>("PerformanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Audience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PerformanceId");

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Domain.Play", b =>
                {
                    b.Property<int>("PlayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lines")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayId");

                    b.ToTable("Play");
                });
#pragma warning restore 612, 618
        }
    }
}
