// <auto-generated />
using JogaresTeatrais.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JogaresTeatrais.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240831155301_AjusteVinculoFaturaDesempenho")]
    partial class AjusteVinculoFaturaDesempenho
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("JogadoresTeatrais.Domain.Entities.Desempenho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Audiencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FaturaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JogarId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FaturaId");

                    b.ToTable("Desempenho");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Audiencia = 55,
                            FaturaId = 1,
                            JogarId = 1
                        },
                        new
                        {
                            Id = 3,
                            Audiencia = 35,
                            FaturaId = 1,
                            JogarId = 2
                        },
                        new
                        {
                            Id = 4,
                            Audiencia = 40,
                            FaturaId = 1,
                            JogarId = 3
                        });
                });

            modelBuilder.Entity("JogadoresTeatrais.Domain.Entities.Fatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fatura");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cliente = "Big Co"
                        });
                });

            modelBuilder.Entity("JogaresTeatrais.Data.Jogar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Linhas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jogar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Linhas = 4024,
                            Nome = "Hamlet",
                            Tipo = "tragedy"
                        },
                        new
                        {
                            Id = 2,
                            Linhas = 2670,
                            Nome = "As You Like It",
                            Tipo = "comedy"
                        },
                        new
                        {
                            Id = 3,
                            Linhas = 3560,
                            Nome = "Othello",
                            Tipo = "tragedy"
                        },
                        new
                        {
                            Id = 4,
                            Linhas = 3227,
                            Nome = "Henry V",
                            Tipo = "history"
                        },
                        new
                        {
                            Id = 5,
                            Linhas = 3560,
                            Nome = "John",
                            Tipo = "history"
                        },
                        new
                        {
                            Id = 6,
                            Linhas = 3718,
                            Nome = "Richard-III",
                            Tipo = "history"
                        });
                });

            modelBuilder.Entity("JogadoresTeatrais.Domain.Entities.Desempenho", b =>
                {
                    b.HasOne("JogadoresTeatrais.Domain.Entities.Fatura", "Fatura")
                        .WithMany("Desempenhos")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("JogadoresTeatrais.Domain.Entities.Fatura", b =>
                {
                    b.Navigation("Desempenhos");
                });
#pragma warning restore 612, 618
        }
    }
}
