// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheatricalPlayersRefactoringKata.API.Data;

#nullable disable

namespace TheatricalPlayersRefactoringKata.API.Data.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvoicePerformance", b =>
                {
                    b.Property<Guid>("InvoicesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PerformancesId")
                        .HasColumnType("uuid");

                    b.HasKey("InvoicesId", "PerformancesId");

                    b.HasIndex("PerformancesId");

                    b.ToTable("PerformanceInvoices", (string)null);
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Core.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Invoices", (string)null);
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Core.Entities.Performance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("Audience")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayId");

                    b.ToTable("Performances", (string)null);
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Core.Entities.Play", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Lines")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Plays", (string)null);
                });

            modelBuilder.Entity("InvoicePerformance", b =>
                {
                    b.HasOne("TheatricalPlayersRefactoringKata.Core.Entities.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheatricalPlayersRefactoringKata.Core.Entities.Performance", null)
                        .WithMany()
                        .HasForeignKey("PerformancesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Core.Entities.Performance", b =>
                {
                    b.HasOne("TheatricalPlayersRefactoringKata.Core.Entities.Play", "Play")
                        .WithMany()
                        .HasForeignKey("PlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Play");
                });
#pragma warning restore 612, 618
        }
    }
}
