// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheatricalPlayersRefactoringKata.Repository;

#nullable disable

namespace TheatricalPlayersRefactoringKata.Repository.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20241110192743_CriarBancoInicial")]
    partial class CriarBancoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("TheatricalPlayersRefactoringKata.Model.Performance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountOwed")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Audience")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("EarnedCredits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Performances");
                });
#pragma warning restore 612, 618
        }
    }
}
